version: "3.0"

services:
  vue:
    build:
      context: vue-ui
    ports:
      - "25000:80"
  api:
    build:
      context: api
    command: uvicorn app:app --host 0.0.0.0

  # build-vue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.build-vue
  #   command: [
  #     "cp", "-a", "/build/dist/.", "/app"
  #   ]
  #   volumes:
  #     - vue-app:/app
volumes:
  vue-app:
