version: "3.0"

services:
  vue:
    build:
      context: vue-ui
    ports:
      - "25000:80"
  api:
    build:
      context: api
    command: uvicorn app:app --host 0.0.0.0
    volumes:
      - ${MINECRAFT_ROOT}:/minecraft
    environment:
      MINECRAFT_DIR: /minecraft
